'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    

    await queryInterface.bulkInsert(
      'Users',
      [
        {
          username: 'Сашулик',
          email: 'a.moramova@gmail.com',
          password: 'fghFGHJ567%^',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          username: 'Тугизик',
          email: 'tugizik@mail.ru',
          password: 'cvbnmFGHJ56789%^',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
      ],
      {}
    );

    await queryInterface.bulkInsert(
      'Dinos',
      [
        {
          name: 'Вовчираптор',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino11.jpg',
          power: '70',
          agility: '10',
          intellect: '90',
          stamina: '50',
          magic: '80',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Аселатопус',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino10.jpg',
          power: '60',
          agility: '100',
          intellect: '90',
          stamina: '90',
          magic: '100',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Катоптера',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino13.jpg',
          power: '60',
          agility: '70',
          intellect: '90',
          stamina: '60',
          magic: '80',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Мифуринхус',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino3.jpg',
          power: '50',
          agility: '60',
          intellect: '90',
          stamina: '50',
          magic: '70',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Настораптос',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino5.jpg',
          power: '50',
          agility: '70',
          intellect: '80',
          stamina: '90',
          magic: '70',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Полинотоп',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino12.jpg',
          power: '60',
          agility: '60',
          intellect: '90',
          stamina: '50',
          magic: '70',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Миламанункул',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino9.jpg',
          power: '60',
          agility: '80',
          intellect: '70',
          stamina: '60',
          magic: '70',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Илинодон',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino8.jpg',
          power: '10',
          agility: '20',
          intellect: '40',
          stamina: '50',
          magic: '20',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Никцераптор',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino4.jpg',
          power: '100',
          agility: '0',
          intellect: '100',
          stamina: '100',
          magic: '100',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Макцераптос',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino1.jpg',
          power: '90',
          agility: '70',
          intellect: '100',
          stamina: '90',
          magic: '100',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Машфоринфус',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino7.jpg',
          power: '80',
          agility: '70',
          intellect: '90',
          stamina: '70',
          magic: '50',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Юрхиозавр',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino6.jpg',
          power: '70',
          agility: '60',
          intellect: '100',
          stamina: '50',
          magic: '80',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Веломонантос',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino2.jpg',
          power: '60',
          agility: '70',
          intellect: '70',
          stamina: '80',
          magic: '60',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Стегонандрий',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino2.jpg',
          power: '70',
          agility: '70',
          intellect: '100',
          stamina: '90',
          magic: '60',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Кирнозавр',
          skills: 'Владеет магией древних',
          image: '/src/public/images/dino2.jpg',
          power: '80',
          agility: '50',
          intellect: '70',
          stamina: '70',
          magic: '60',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
      ],
      {}
    );


  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Dinos', null, {});
    await queryInterface.bulkDelete('Users', null, {});
  }
};
