'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    

    await queryInterface.bulkInsert(
      'Users',
      [
        {
          username: 'Сашулик',
          email: 'a.moramova@gmail.com',
          password: 'fghFGHJ567%^',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          username: 'Тугизик',
          email: 'tugizik@mail.ru',
          password: 'cvbnmFGHJ56789%^',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
      ],
      {}
    );

    await queryInterface.bulkInsert(
      'Dinos',
      [
        {
          name: 'Вовчираптор',
          skills: 'Обладает способностью превращаться в камень для повышения защиты. Этот динозавр может использовать свои каменные атаки для создания преград и блокировки уронов.',
          image: '/images/dino11.png',
          power: '70',
          agility: '10',
          intellect: '90',
          stamina: '50',
          magic: '80',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Аселатопус',
          skills: 'Обладает способностью к быстрому перемещению и атаке с электрическими разрядами. Его молниеносные атаки наносят урон врагам и могут временно парализовать их.',
          image: '/images/dino15.png',
          power: '60',
          agility: '100',
          intellect: '90',
          stamina: '90',
          magic: '100',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Катоптера',
          skills: 'Может создавать снежные бурю и замораживать врагов на месте. Это делает ее отличной защитницей и контроллершей, которая помогает команде удерживать дистанцию от противников.',
          image: '/images/dino13.png',
          power: '60',
          agility: '70',
          intellect: '90',
          stamina: '60',
          magic: '80',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Мифуринхус',
          skills: 'Этот динозавр может управлять песком и создавать песчаные бурю, чтобы скрыть движение своей команды. Его способности идеально подходят для ловушек и стратегического маневрирования на поле боя.',
          image: '/images/dino3.png',
          power: '50',
          agility: '60',
          intellect: '90',
          stamina: '50',
          magic: '70',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Настораптос',
          skills: 'Есть скрытая способность летать на высоте, наблюдая за врагами и передавая информацию команде. Его воздушные атаки позволяют ему атаковать с неожиданного направления, что делает его незаменимым разведчиком.',
          image: '/images/dino5.png',
          power: '50',
          agility: '70',
          intellect: '80',
          stamina: '90',
          magic: '70',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Полинотоп',
          skills: 'Умеет сливаться с окружением, делая себя практически невидимым. Его шипы могут сверкать при атаке, отвлекая внимание врагов. Время от времени получает щит, защищающий от урона.',
          image: '/images/dino12.png',
          power: '60',
          agility: '60',
          intellect: '90',
          stamina: '50',
          magic: '70',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Миламанункул',
          skills: 'Этот динозавр обладает выдающейся скоростью и маневренностью. Он может совершать короткие, резкие рывки, чтобы избегать врагов и легко преодолевать препятствия. Его скорость позволяет ему быть идеальным разведчиком в игре.',
          image: '/images/dino9.png',
          power: '60',
          agility: '80',
          intellect: '70',
          stamina: '60',
          magic: '70',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Илинодон',
          skills: 'Это динозавр, способный издавать мощные звуки, дезориентируя врагов и увеличивая боевой дух союзников. Его способности отлично подходят для поддержки команды и создания хаоса среди противников.',
          image: '/images/dino8.png',
          power: '10',
          agility: '20',
          intellect: '40',
          stamina: '50',
          magic: '20',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Никцераптор',
          skills: 'Обладает способностью восстанавливать здоровье союзников, поглощая природные ресурсы. Он может создавать обширные зеленые зоны, увеличивающие силу и защиту своей команды.',
          image: '/images/dino4.png',
          power: '100',
          agility: '0',
          intellect: '100',
          stamina: '100',
          magic: '100',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Макцераптос',
          skills: 'Обладает высоким интеллектом, помогает команде разрабатывать стратегии. Его голова может наносить мощные удары, которые сбивают противников с ног. Умеет вдохновлять союзников, повышая их боевые способности.',
          image: '/images/dino1.png',
          power: '90',
          agility: '70',
          intellect: '100',
          stamina: '90',
          magic: '100',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Машфоринфус',
          skills: 'Может выдыхать ядовитый газ, который ослабляет врагов и снижает их возможности на время. Способности идеально подходят для контроля территории и создания зон, опасных для противников.',
          image: '/images/dino7.png',
          power: '80',
          agility: '70',
          intellect: '90',
          stamina: '70',
          magic: '50',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Юрхиозавр',
          skills: 'Обладает уровнем защиты, позволяющим ему игнорировать некоторые атаки. Его способности иммунитета к статусным эффектам делают его бесценным в бою.',
          image: '/images/dino6.png',
          power: '70',
          agility: '60',
          intellect: '100',
          stamina: '50',
          magic: '80',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Веломонантос',
          skills: 'Снасти сильное заклинание привлечение, которое заставляет врагов сражаться друг с другом в течение короткого времени. Это позволяет команде избежать урона.',
          image: '/images/dino2.png',
          power: '60',
          agility: '70',
          intellect: '70',
          stamina: '80',
          magic: '60',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Стегонандрий',
          skills: 'Обладает способностью к быстрой регенерации, восстанавливая здоровье даже во время боя. Его удары наносят урон и замедляют врагов.',
          image: '/images/dino16.png',
          power: '70',
          agility: '70',
          intellect: '100',
          stamina: '90',
          magic: '60',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
        {
          name: 'Кирнозавр',
          skills: 'Обладает массивным телом, что позволяет прорывать преграды и наносить колоссальный урон. Его длинная шея помогает достигать высоких мест для сбора пищи или атаки сверху. Мгновенно восстанавливает энергию из окружающей среды.',
          image: '/images/dino14.png',
          power: '80',
          agility: '50',
          intellect: '70',
          stamina: '70',
          magic: '60',
          createdAt: Sequelize.fn('NOW'),
          updatedAt: Sequelize.fn('NOW'),
        },
      ],
      {}
    );


  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Dinos', null, {});
    await queryInterface.bulkDelete('Users', null, {});
  }
};
